"""Backtesting engine for strategy evaluation.

Provides the core backtesting loop that iterates through historical bars,
invokes strategy logic, executes simulated orders, and tracks portfolio
performance over time.
"""

from dataclasses import dataclass, field
from datetime import date as DateType
from enum import Enum
from typing import Any, Protocol

import pandas as pd
from loguru import logger


class Signal(Enum):
    """Trading signal generated by a strategy."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class Trade:
    """Record of an executed trade.

    Attributes:
        date: Execution date of the trade.
        symbol: Ticker symbol of the traded instrument.
        direction: Either 'buy' or 'sell'.
        price: Execution price after slippage.
        quantity: Number of shares traded.
        commission: Commission fee paid.
        slippage: Slippage cost incurred.
    """

    date: DateType
    symbol: str
    direction: str
    price: float
    quantity: int
    commission: float
    slippage: float


@dataclass
class Position:
    """Current holding position for a symbol.

    Attributes:
        symbol: Ticker symbol.
        quantity: Number of shares held.
        avg_cost: Average cost per share (including commission).
        current_price: Latest market price.
        unrealized_pnl: Unrealized profit/loss based on current price.
    """

    symbol: str
    quantity: int
    avg_cost: float
    current_price: float

    @property
    def unrealized_pnl(self) -> float:
        """Calculate unrealized profit and loss."""
        return (self.current_price - self.avg_cost) * self.quantity


@dataclass
class BacktestResult:
    """Results container for a completed backtest.

    Attributes:
        trades: List of all executed trades.
        equity_curve: Daily portfolio equity as a time series.
        metrics: Dictionary of performance metrics.
    """

    trades: list[Trade] = field(default_factory=list)
    equity_curve: pd.Series = field(default_factory=lambda: pd.Series(dtype=float))
    metrics: dict[str, Any] = field(default_factory=dict)


class Strategy(Protocol):
    """Protocol defining the strategy interface.

    Strategies must implement on_bar to generate trading signals.
    """

    def on_bar(
        self, index: int, row: pd.Series, engine: "BacktestEngine"
    ) -> Signal: ...


class BacktestEngine:
    """Event-driven backtesting engine.

    Simulates trading through historical price data bar by bar, executing
    orders with realistic transaction costs including commission, slippage,
    and stamp tax (sell-side, A-share market rule).

    Args:
        initial_capital: Starting cash amount (default 1,000,000).
        commission_rate: Commission rate per trade (default 0.0003, i.e. 0.03%).
        slippage: Slippage as a fraction of price (default 0.001, i.e. 0.1%).
        stamp_tax: Stamp tax rate on sell orders only (default 0.001, i.e. 0.1%).

    Example:
        >>> engine = BacktestEngine(initial_capital=500_000)
        >>> result = engine.run(my_strategy, price_data, "000001.SZ")
    """

    def __init__(
        self,
        initial_capital: float = 1_000_000,
        commission_rate: float = 0.0003,
        slippage: float = 0.001,
        stamp_tax: float = 0.001,
    ) -> None:
        self.initial_capital = initial_capital
        self.commission_rate = commission_rate
        self.slippage = slippage
        self.stamp_tax = stamp_tax

        self._cash: float = initial_capital
        self._positions: dict[str, Position] = {}
        self._trades: list[Trade] = []
        self._equity_curve: dict[DateType, float] = {}

    @property
    def cash(self) -> float:
        """Current available cash."""
        return self._cash

    @property
    def positions(self) -> dict[str, Position]:
        """Current open positions."""
        return self._positions

    def get_position(self, symbol: str) -> Position | None:
        """Get position for a symbol, or None if not held."""
        return self._positions.get(symbol)

    def run(
        self, strategy: Strategy, data: pd.DataFrame, symbol: str
    ) -> BacktestResult:
        """Run the backtest over the provided data.

        Iterates through each bar in the DataFrame, calls the strategy's
        on_bar method to get a signal, and executes the corresponding order.

        Args:
            strategy: Strategy instance implementing the on_bar method.
            data: DataFrame with columns including 'open', 'high', 'low',
                'close', 'volume'. Index should be datetime or date.
            symbol: Ticker symbol being traded.

        Returns:
            BacktestResult containing trades, equity curve, and metrics.

        Raises:
            ValueError: If data is empty or missing required columns.
        """
        if data.empty:
            raise ValueError("Input data must not be empty.")

        required_columns = {"open", "high", "low", "close", "volume"}
        missing = required_columns - set(data.columns)
        if missing:
            raise ValueError(f"Data is missing required columns: {missing}")

        # Reset state for new run
        self._cash = self.initial_capital
        self._positions = {}
        self._trades = []
        self._equity_curve = {}

        logger.info(
            f"Starting backtest for {symbol} | "
            f"Capital: {self.initial_capital:,.0f} | "
            f"Bars: {len(data)}"
        )

        for idx in range(len(data)):
            row = data.iloc[idx]
            bar_date = data.index[idx]

            # Update current price for existing positions
            if symbol in self._positions:
                self._positions[symbol].current_price = row["close"]

            # Get strategy signal
            try:
                signal = strategy.on_bar(idx, row, self)
            except Exception as e:
                logger.error(f"Strategy error at bar {idx}: {e}")
                signal = Signal.HOLD

            # Execute signal
            if signal == Signal.BUY:
                self._execute_buy(symbol, row["close"], bar_date)
            elif signal == Signal.SELL:
                self._execute_sell(symbol, row["close"], bar_date)

            # Record daily equity
            equity = self._calculate_equity(row["close"], symbol)
            self._equity_curve[bar_date] = equity

        # Build result
        equity_series = pd.Series(self._equity_curve, dtype=float)
        equity_series.index.name = "date"

        logger.info(
            f"Backtest complete | Trades: {len(self._trades)} | "
            f"Final equity: {equity_series.iloc[-1]:,.2f}"
        )

        from .metrics import calculate_metrics

        metrics = calculate_metrics(equity_series, self._trades)

        return BacktestResult(
            trades=self._trades,
            equity_curve=equity_series,
            metrics=metrics,
        )

    def _execute_buy(
        self, symbol: str, price: float, bar_date: DateType
    ) -> None:
        """Execute a buy order with commission and slippage.

        Buys as many shares as affordable in lots of 100 (A-share rule).

        Args:
            symbol: Ticker symbol to buy.
            price: Market price at order time.
            bar_date: Date of the trade execution.
        """
        # Apply slippage (buy at higher price)
        exec_price = price * (1.0 + self.slippage)

        # Calculate max affordable quantity (lots of 100)
        max_cost_per_share = exec_price * (1.0 + self.commission_rate)
        if max_cost_per_share <= 0:
            return

        max_quantity = int(self._cash / max_cost_per_share)
        quantity = (max_quantity // 100) * 100  # Round to lots of 100

        if quantity <= 0:
            logger.debug(f"Insufficient cash to buy {symbol} at {exec_price:.2f}")
            return

        commission = exec_price * quantity * self.commission_rate
        total_cost = exec_price * quantity + commission
        slippage_cost = (exec_price - price) * quantity

        self._cash -= total_cost

        # Update or create position
        if symbol in self._positions:
            pos = self._positions[symbol]
            total_quantity = pos.quantity + quantity
            pos.avg_cost = (
                (pos.avg_cost * pos.quantity + exec_price * quantity) / total_quantity
            )
            pos.quantity = total_quantity
            pos.current_price = price
        else:
            self._positions[symbol] = Position(
                symbol=symbol,
                quantity=quantity,
                avg_cost=exec_price,
                current_price=price,
            )

        trade = Trade(
            date=bar_date,
            symbol=symbol,
            direction="buy",
            price=exec_price,
            quantity=quantity,
            commission=commission,
            slippage=slippage_cost,
        )
        self._trades.append(trade)

        logger.debug(
            f"BUY {symbol} | Qty: {quantity} | Price: {exec_price:.4f} | "
            f"Commission: {commission:.2f} | Cash remaining: {self._cash:,.2f}"
        )

    def _execute_sell(
        self, symbol: str, price: float, bar_date: DateType
    ) -> None:
        """Execute a sell order with commission, slippage, and stamp tax.

        Sells the entire position. Stamp tax is applied on sell only
        (A-share market rule).

        Args:
            symbol: Ticker symbol to sell.
            price: Market price at order time.
            bar_date: Date of the trade execution.
        """
        position = self._positions.get(symbol)
        if position is None or position.quantity <= 0:
            logger.debug(f"No position to sell for {symbol}")
            return

        # Apply slippage (sell at lower price)
        exec_price = price * (1.0 - self.slippage)
        quantity = position.quantity

        commission = exec_price * quantity * self.commission_rate
        stamp_tax_cost = exec_price * quantity * self.stamp_tax
        slippage_cost = (price - exec_price) * quantity

        proceeds = exec_price * quantity - commission - stamp_tax_cost
        self._cash += proceeds

        # Remove position
        del self._positions[symbol]

        trade = Trade(
            date=bar_date,
            symbol=symbol,
            direction="sell",
            price=exec_price,
            quantity=quantity,
            commission=commission + stamp_tax_cost,
            slippage=slippage_cost,
        )
        self._trades.append(trade)

        logger.debug(
            f"SELL {symbol} | Qty: {quantity} | Price: {exec_price:.4f} | "
            f"Commission: {commission:.2f} | Stamp tax: {stamp_tax_cost:.2f} | "
            f"Cash: {self._cash:,.2f}"
        )

    def _calculate_equity(self, current_price: float, symbol: str) -> float:
        """Calculate total portfolio equity.

        Args:
            current_price: Current market price for the active symbol.
            symbol: The symbol being backtested.

        Returns:
            Total equity (cash + market value of positions).
        """
        equity = self._cash
        for sym, pos in self._positions.items():
            if sym == symbol:
                equity += pos.quantity * current_price
            else:
                equity += pos.quantity * pos.current_price
        return equity
